# Generated by Django 2.2.5 on 2019-12-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tagPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(choices=[(1, '西游记'), (2, '三国演义'), (3, '红楼梦'), (4, '水浒传')], default=3, verbose_name='书本id')),
                ('episode', models.IntegerField(default=1, verbose_name='集数')),
                ('pic_url', models.TextField(default='', verbose_name='图片名称')),
                ('pos', models.TextField(default='', verbose_name='红框位置')),
                ('name_ai', models.TextField(default='', verbose_name='检测出名称')),
                ('name_true', models.TextField(default='', verbose_name='真实名称')),
            ],
        ),
    ]
