# Generated by Django 2.2.5 on 2019-12-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpic',
            name='name_true',
            field=models.TextField(blank=True, default='', verbose_name='真实名称'),
        ),
    ]
