# Generated by Django 2.2.5 on 2019-12-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0004_auto_20191203_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default='', verbose_name='用户名')),
                ('password', models.TextField(default='', verbose_name='密码')),
                ('last_work', models.TextField(default='', verbose_name='最后录到的记录')),
                ('status', models.IntegerField(default=1, verbose_name='用户登陆状态')),
            ],
        ),
        migrations.AddField(
            model_name='tagpic',
            name='users',
            field=models.ManyToManyField(to='tag.User', verbose_name='标记用户'),
        ),
    ]
