# Generated by Django 2.2.5 on 2019-12-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_auto_20191204_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(choices=[(0, '红楼梦'), (1, '西游记'), (2, '水浒传'), (3, '三国演义')], default=3, verbose_name='书本id')),
                ('name', models.TextField(default='集', verbose_name='集数名称')),
                ('episode_index', models.IntegerField(default=1, verbose_name='集数')),
            ],
        ),
        migrations.AlterField(
            model_name='tagpic',
            name='book_id',
            field=models.IntegerField(choices=[(0, '红楼梦'), (1, '西游记'), (2, '水浒传'), (3, '三国演义')], default=3, verbose_name='书本id'),
        ),
        migrations.AlterField(
            model_name='tagpic',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Episode', verbose_name='集'),
        ),
    ]
