# Generated by Django 2.2.5 on 2019-12-09 03:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_auto_20191206_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagpic',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 3, 45, 0, 160867, tzinfo=utc), verbose_name='标记时间'),
        ),
    ]
